before_script:
      # Print out python version for debugging
    - python -V
      # clone raven
    - git clone https://github.com/idaholab/raven.git
    - cd raven
      # we technically still need moose for running the tests, currently
    - git checkout master
    - git clean -xfd
      # check that we have conda
    - export PATH=$HOME/miniconda2/bin:$PATH
    - if which conda 2> /dev/null; then
        echo "Conda found!";
        conda update conda;
      else
        echo "ERROR Conda not found!";
        exit 404;
      fi
      # create libraries or create them
    - ./scripts/establish_conda_env.sh --install --conda-defs $HOME/miniconda2/etc/profile.d/conda.sh
    - ./build_raven
      # Install plugin branch ...
    - cd scripts
    - python install_plugins.py -s ../../
      # return to project path main dir
    - cd ../..

test:
    script:
      - cd raven
      - ./run_tests -j4 --re=plugins/SR2ML --no-color # does this return a failed status?
